name: Pull Request Check

on:
  pull_request:
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./app/requirements.txt  

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    
    - name: Run tests
      run: |
        python -m pytest  ./tests/test_app.py

